#!/usr/bin/env node
/**
 * import_score.mjs — Correct and validate copied Canopy studio score exports.
 *
 * A studio export is a self-contained ES module. Its one project-specific bit is
 * the very first line — the `import * as Tone from "<path>"`. Because the studio
 * serves several games, the Tone specifier can differ between destinations, so a
 * copy-pasted file frequently points at the previous project's Tone (or at a
 * stale relative path) and is otherwise subtly stale. `scoreTiming.test.js` pins
 * the per-voice ordering / collision fixes that live in the export's engine, so a
 * stale export fails that test.
 *
 * This script makes a copied file correct and verifiable:
 *
 *   - Rewrites the Tone import to the correct path for THIS repo (computed
 *     relative to the destination file, so it is never hand-typed).
 *   - Prepends a `GENERATED` provenance header carrying a SHA-256 of the module
 *     body, so hand-edits / drift become a one-line check (`--check`).
 *   - Optionally runs the read-only `scoreTiming` guard test against the result,
 *     so a regressed export fails loudly instead of shipping.
 *
 * The one bit you must still do manually is register the track in `SCORE_MODULES`
 * in src/runtime/audio/musicDirector.js (see dev/docs/musicSystem.md).
 *
 * Usage:
 *   node dev/scripts/import_score.mjs <file...>                     correct in place
 *   node dev/scripts/import_score.mjs --out dir/name.score.js <src> write to a path
 *   node dev/scripts/import_score.mjs --check <file...>             read-only verify
 *
 * Options:
 *   --out <path>     Destination file. Defaults to the source path (in place).
 *   --tone <path>    Tone entry the import should target (default: the repo's
 *                    vendored Tone, src/vendor/tone/index.js).
 *   --name <name>    Module name stamped in the header. Defaults to the output
 *                    basename without `.score.js`.
 *   --no-test        Skip the read-only scoreTiming guard test.
 *   --check          Validate only: verify the Tone import + provenance hash and
 *                    run the guard test. Never writes.
 *
 * Exit code is 0 when everything passes, 1 when a guard test fails (the export is
 * stale — re-export from the studio rather than hand-patching the file).
 */

import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

// ── Location context ─────────────────────────────────────────────────────────

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..');
const DEFAULT_TONE = path.join('src', 'vendor', 'tone', 'index.js');

// ── Regexes ────────────────────────────────────────────────────────────────

// A canonical Tone import: `import * as Tone from "...";` (allow optional `;`).
const TONE_IMPORT_RE = /^import\s+\*\s+as\s+Tone\s+from\s+["'][^"']+["']\s*;?\s*$/m;
// Any import whose specifier mentions "tone".
const ANY_TONE_IMPORT_RE = /^import\b[^\n]*?from\s+["'][^"']*tone[^"']*["']\s*;?\s*$/im;
// The generated provenance header block (may be absent on hand-copied files).
const HEADER_RE = /^\/\*\s*GENERATED[\s\S]*?\*\/\s*\r?\n?/m;

// ── Small IO helpers ────────────────────────────────────────────────────────

function fail(msg) {
  console.error(`[import_score] ${msg}`);
  process.exitCode = 1;
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** The module body = source minus any leading generated header. */
function bodyOf(source) {
  return source.replace(HEADER_RE, '');
}

/** Correct the Tone import line to point at `toneAbs`, relative to `destAbs`. */
function rewriteToneImport(source, toneAbs, destAbs) {
  const destDir = path.dirname(destAbs);
  let rel = path
    .relative(destDir, toneAbs)
    .split(path.sep)
    .join('/');
  if (!rel.startsWith('.')) rel = `./${rel}`;

  let re = source.match(TONE_IMPORT_RE)
    ? TONE_IMPORT_RE
    : source.match(ANY_TONE_IMPORT_RE)
      ? ANY_TONE_IMPORT_RE
      : null;
  if (!re) {
    return { ok: false, msg: 'no Tone import found — not a score module?' };
  }
  const replacement = `import * as Tone from "${rel}";`;
  const rewritten = source.replace(re, replacement);
  return { ok: true, source: rewritten, rel };
}

/** Build the provenance header for a module body. */
function buildHeader({ name, toneRel, body, importedAt }) {
  const hash = sha256(body);
  return [
    '/* GENERATED by Canopy studio export — do not hand-edit below this line.',
    `   module:        ${name}`,
    `   tone import:   ${toneRel}  (rewritten by import_score.mjs)`,
    `   contentSha256: ${hash}`,
    `   imported:      ${importedAt}`,
    '*/',
    '',
  ].join('\n');
}

/** Run the read-only scoreTiming guard test; returns { ok, failCount }. */
function runGuardTest() {
  const testFile = path.join('dev', 'tests', 'game', 'music', 'scoreTiming.test.js');
  const res = spawnSync(process.execPath, ['--test', testFile], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    timeout: 120_000,
  });
  const out = `${res.stdout || ''}${res.stderr || ''}`;
  const m = out.match(/ℹ fail\s+(\d+)/);
  const failCount = m ? Number(m[1]) : (res.status === 0 ? 0 : -1);
  return { ok: res.status === 0 && failCount === 0, failCount };
}

// ── Command modes ───────────────────────────────────────────────────────────

function collectArgs(argv) {
  const args = argv.slice(2);
  const opts = { files: [], out: null, tone: DEFAULT_TONE, name: null, noTest: false, check: false };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--out') opts.out = args[++i];
    else if (a === '--tone') opts.tone = args[++i];
    else if (a === '--name') opts.name = args[++i];
    else if (a === '--no-test') opts.noTest = true;
    else if (a === '--check') opts.check = true;
    else if (a === '--help' || a === '-h') { usage(); process.exit(0); }
    else opts.files.push(a);
  }
  if (!opts.files.length) {
    usage();
    process.exit(1);
  }
  return opts;
}

function usage() {
  console.log(`Usage:
  node dev/scripts/import_score.mjs <file...>              correct in place
  node dev/scripts/import_score.mjs --out <path> <src>    write to a path
  node dev/scripts/import_score.mjs --check <file...>     read-only verify

Options:
  --out <path>   Destination file (default: source path, in place)
  --tone <path>  Tone entry to target (default: src/vendor/tone/index.js)
  --name <name>  Module name stamped in the header
  --no-test      Skip the scoreTiming guard test
  --check        Verify only; never writes`);
}

function reportGuard(name, guard) {
  if (!guard.failCount) {
    console.log(`  guard: PASS (scoreTiming ${name})`);
  } else {
    const label = guard.failCount === -1 ? 'could not run' : `${guard.failCount} fail(s)`;
    console.error(`  guard: ${label}`);
    console.error('  This export is stale — re-export from the studio that carries the');
    console.error('  per-voice ordering / collision fixes. Do NOT hand-patch this file.');
  }
}

// ── Invocation ───────────────────────────────────────────────────────────────

const opts = collectArgs(process.argv);
let anyFail = false;

for (const srcFile of opts.files) {
  const srcAbs = path.resolve(REPO_ROOT, srcFile);
  if (!existsSync(srcAbs) || !statSync(srcAbs).isFile()) {
    fail(`source not found: ${srcFile}`);
    anyFail = true;
    continue;
  }

  const destAbs = path.resolve(REPO_ROOT, opts.out || srcFile);
  const name = opts.name || path.basename(destAbs).replace(/\.score\.js$/, '');
  const toneAbs = path.resolve(REPO_ROOT, opts.tone);
  const src = readFileSync(srcAbs, 'utf8');

  if (opts.check) {
    // ── Verify only ──
    console.log(`Checking ${path.relative(REPO_ROOT, destAbs)} (${name})`);
    const body = bodyOf(src);
    const header = src.match(HEADER_RE)?.[0] || '';
    const hashMatch = header.match(/contentSha256:\s*([0-9a-f]{64})/);
    if (!hashMatch) {
      console.log('  provenance: none (not yet imported; run without --check to add)');
    } else if (hashMatch[1] !== sha256(body)) {
      console.error('  provenance: MISMATCH — file body changed since import');
      anyFail = true;
    } else {
      console.log('  provenance: ok (hash matches body)');
    }

    const toneRes = rewriteToneImport(src, toneAbs, destAbs);
    if (!toneRes.ok) {
      fail(`${name}: ${toneRes.msg}`);
      anyFail = true;
      continue;
    }
    const expect = `import * as Tone from "${toneRes.rel}";`;
    if (!src.includes(expect)) {
      console.log(`  tone import: ${expect} (will be rewritten on import)`);
    } else {
      console.log(`  tone import: ok (${expect})`);
    }

    if (!opts.noTest) {
      const guard = runGuardTest();
      reportGuard(name, guard);
      if (!guard.ok) anyFail = true;
    }
    continue;
  }

  // ── Correct (import) ──
  console.log(`Importing ${path.relative(REPO_ROOT, srcAbs)} -> ${path.relative(REPO_ROOT, destAbs)} (${name})`);

  const toneRes = rewriteToneImport(src, toneAbs, destAbs);
  if (!toneRes.ok) {
    fail(`${name}: ${toneRes.msg}`);
    anyFail = true;
    continue;
  }

  const body = toneRes.source;
  const header = buildHeader({
    name,
    toneRel: toneRes.rel,
    body,
    importedAt: new Date().toISOString(),
  });
  writeFileSync(destAbs, header + body);

  console.log(`  tone import: ${toneRes.rel}`);
  console.log(`  provenance:  stamped contentSha256=${sha256(body)}`);

  if (!opts.noTest) {
    const guard = runGuardTest();
    reportGuard(name, guard);
    if (!guard.ok) anyFail = true;
  }
  console.log(`  wrote ${path.relative(REPO_ROOT, destAbs)}`);
}

process.exitCode = anyFail ? 1 : 0;
